/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_multimedia;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamImageTransformer;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.github.sarxos.webcam.WebcamUtils;
import com.github.sarxos.webcam.util.jh.JHGrayFilter;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author jcsp0003
 */
public class VentanaPrincipalJFrame extends javax.swing.JFrame {

    private Webcam cam;
    private Dimension ds;
    private Dimension cs;
    private WebcamPanel wcPanel;
    private Thread t;
    private boolean recording;
    private Ajustes ajustes;

    private hiloVideo hiloDeVideo;

    private String formatoImagen;

    public VentanaPrincipalJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        comprobarWebCam();
        hiloDeVideo = null;
        recording = false;
        ajustes = new Ajustes(this);
        formatoImagen = "bmp";
    }

    private void comprobarWebCam() {
        Webcam webcam = Webcam.getDefault();
        if (webcam == null) {
            VentanaError error = new VentanaError("No se detecta ninguna web-cam");
            error.mostrar();
        } else {
            cam = Webcam.getDefault();
            ds = new Dimension(760, 422);
            cs = WebcamResolution.VGA.getSize();

            /* Prueba marco */
            //JFrame window = new JFrame("Test Transformer");
            wcPanel = new WebcamPanel(cam, ds, false);

            /* Prueba marco */
            wcPanel.setFillArea(true);

            jPanel1.add(wcPanel);

            /* Prueba marco */
            //window.pack();
            //window.setVisible(true);
            //window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            t = new Thread() {
                @Override
                public void run() {
                //    wcPanel.start();
                }
            };
            t.setDaemon(true);
            t.start();

            cam.setViewSize(cs);
            wcPanel.setFitArea(true);
            jPanel1.setLayout(new FlowLayout());
            jPanel1.add(wcPanel);
            refrescarImagen();    
        }
    }
    
    private void refrescarImagen() {
    
        // Esto no se si está hecho
         if (jPanel1 instanceof WebcamPanel) ((WebcamPanel)jPanel1).stop();
        remove(jPanel1);
        //dalt = updateResolution(activeWebcam,jComboBox2);
        //ComboBoxModel cbm = jComboBox2.getModel();
        
        cam.setImageTransformer(new TransformarImg()); // Transformaciones.
        cam.open(); // Abre la webcam al mundo.

        jPanel1 = new WebcamPanel(cam);
//        ((WebcamPanel)jPanel1).setMirrored(jCheckBox1.isSelected());
//        ((WebcamPanel)jPanel1).setFPSDisplayed(jCheckBox2.isSelected());
//        ((WebcamPanel)jPanel1).setDisplayDebugInfo(jCheckBox2.isSelected());
//        jList1.setSelectedIndex(0);
//        jList2.setSelectedIndex(0);
//        constructLayout();
//        getListWebcam(jComboBox1, activeWebcam);
//        jComboBox2.setModel(cbm);
//        updateTemplates(jList2,directoryListing("templates",".png"));
        revalidate();
        repaint();
        insertarMarco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jButton3.setText("Foto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Video");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("Ajustes");
        jButton2.setMaximumSize(new java.awt.Dimension(55, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(55, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(55, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String nombre = String.format("captura-%d.jpg", System.currentTimeMillis());
        WebcamUtils.capture(cam, nombre, formatoImagen);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (!recording) {
            recording = true;
            hiloDeVideo = new hiloVideo(cam);
            Thread th = new Thread(hiloDeVideo);
            th.start();
            jButton4.setText("Parar");
        } else {
            jButton4.setText("Video");
            hiloDeVideo.parar();
            recording = false;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ajustes.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void setFormatoImagen(String form) {
        this.formatoImagen = form;
    }

    public void mostrarFPS(boolean acction) {
        wcPanel.setFPSDisplayed(acction);
    }
    
    private void insertarMarco(){
            // Usar ésto para cargar de una lista de marcos (mas adelante) (String)jList2.getModel().getElementAt(jList2.getSelectedIndex())) + ".png"
            
            // Se aplica marco si la cam está activa ( y si hay alguno seleccionado (mas adelante) y se desactiva en caso contrario
            if (cam != null) {
                ((TransformarImg)cam.getImageTransformer()).setTemplate("Pussies.png");
            } else {
                ((TransformarImg)cam.getImageTransformer()).setTemplate(null);
            }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new VentanaPrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
